### ISSUE TITLE
希望增加查询玩家任务状态的节点，用于判断玩家上次走剧情进行到哪个任务节点

### ISSUE THREAD

**Issue by longhuan1999** [liujiaqi7998/node-red-easy-grasscutters#1]
类似这样，最好还能增加对任务是否添加（存在）的检查：
输入：msg.payload.Quest_id、msg.payload.player
输出：msg.payload.state：NONE(正常)、UNSTARTED(未开始)、UNFINISHED(未完成)、FINISHED(完成)、FAILED(失败)、NOTADDED(未添加)

我用 OnQuestChange 节点同时检测不同的状态实现了类似的功能，但不稳定且不规范

**Comment by liujiaqi7998** [comment]
好的，我会更新这个功能
其实，我没有设计这种查询的功能主要是防止用户高速频繁调用造成系统卡死。
但是既然有需要，那我就把这个功能加上去。

**Comment by longhuan1999** [comment]
> 好的，我会更新这个功能 其实，我没有设计这种查询的功能主要是防止用户高速频繁调用造成系统卡死。 但是既然有需要，那我就把这个功能加上去。

谢谢你考虑更新这个功能，如果不是对Java和Grasscutter不熟，我其实也是可以帮忙的
我觉得这个功能还是必要的，至于查询导致的性能问题也可以让设计流程和开服的人考虑和抉择
如果只是自己和朋友用的话就更不用担心性能问题了

**Comment by liujiaqi7998** [comment]
嗯，你说的对，不规范使用所造成的卡顿，应该是使用者的问题。我会在近期添加这个功能。
